# Generated by Django 4.1.7 on 2023-04-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Title', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Year', models.IntegerField(null=True)),
                ('Actors', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
                ('Runtime', models.CharField(max_length=100)),
                ('Censor', models.CharField(max_length=100)),
                ('Total_Gross', models.CharField(max_length=100)),
                ('main_genre', models.CharField(max_length=100)),
                ('side_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
